- name: Install packages
  apt:
    name:
      - openssh-server
      - curl
      - git
    state: present
    update_cache: true

- name: Start SSH service
  service:
    name: ssh
    state: started
    enabled: true
